name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.version }}, ${{ matrix.gemfile }}
    strategy:
      matrix:
        version: [2.5, 2.6, 2.7]
        gemfile: [Gemfile_ar41, Gemfile_ar50, Gemfile_ar51]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: ${{ matrix.version }}
          # bundler-cache: true
      - name: Gem?
        run: |
          gem --version
          gem update --system
      - name: Install dependencies
        run: |
          export BUNDLE_GEMFILE=${GITHUB_WORKSPACE}/${{ matrix.gemfile }}
          rm -f ${GITHUB_WORKSPACE}/Gemfile.lock
          gem install bundler
          gem install jekyll
          bundle
      - name: Run Tests
        run: |
          bundle exec rake test
