name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.version }}
    strategy:
      matrix:
        version: [2.4, 2.5, 2.6, 2.7]
        gemfile: [Gemfile_ar41, Gemfile_ar50, Gemfile_ar51, Gemfile_ar_master]

    steps:
      - uses: actions/checkout@v2
      - name: Set gemfile 
        run: export BUNDLE_GEMFILE=$PWD/${{ matrix.gemfile}}
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rake test
